version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back-net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT_UI}:${PORT_UI}/tcp
    networks:
      - front-net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - back-net
      - front-net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - back-net
      - front-net

volumes:
  post_db:

networks:
  back-net:
  front-net:
